# Generated by Django 4.2.3 on 2023-11-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='category',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Sci-fi', 'Sci-fi'), ('Action', 'Action'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Comedy', 'Comedy')], default=None, max_length=100),
        ),
    ]
